spring.application.name=TiendaLevelUp

# ==========================================
# Configuración de Base de Datos (Oracle Cloud)
# ==========================================
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:oracle:thin:@tiendalevelup_low?TNS_ADMIN=C:/OracleWallets/Wallet_tiendalevelup
spring.datasource.username=ADMIN
spring.datasource.password=Tiendalevelup1.
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# Dialecto e impresión de SQL
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# ==========================================
# Configuración de RabbitMQ (DLQ + Retry)
# ==========================================
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Modo de confirmación manual y fair dispatch
spring.rabbitmq.listener.simple.acknowledge-mode=manual
spring.rabbitmq.listener.simple.prefetch=1

# Configuración de Reintentos (Exponential Backoff)
spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.retry.initial-interval=1000
spring.rabbitmq.listener.simple.retry.max-interval=10000
spring.rabbitmq.listener.simple.retry.multiplier=2.0
spring.rabbitmq.listener.simple.retry.max-attempts=3

# ==========================================
# Servidor y Documentación Swagger
# ==========================================
server.port=8082

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html