spring.application.name=TiendaLevelUp

# Para que Hibernate cree automáticamente las tablas en Oracle Cloud
spring.jpa.hibernate.ddl-auto=update

# Conexión Oracle Cloud con el nuevo Wallet
spring.datasource.url=jdbc:oracle:thin:@tiendalevelup_low?TNS_ADMIN=C:/OracleWallets/Wallet_tiendalevelup
spring.datasource.username=ADMIN
spring.datasource.password=Tiendalevelup1.
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# Dialecto de Hibernate para Oracle
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

server.port=8082

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Swagger / SpringDoc
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=tienda/swagger-ui.html